# Generated by Django 2.2.19 on 2021-03-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('wei', models.IntegerField()),
                ('hei', models.IntegerField()),
                ('bp', models.IntegerField()),
                ('sug', models.IntegerField()),
                ('tem', models.IntegerField()),
                ('hae', models.IntegerField()),
                ('bmi', models.DecimalField(decimal_places=1, max_digits=4)),
                ('dia', models.DecimalField(decimal_places=1, max_digits=4)),
                ('typ', models.DecimalField(decimal_places=1, max_digits=4)),
                ('hea', models.DecimalField(decimal_places=1, max_digits=4)),
                ('ane', models.DecimalField(decimal_places=1, max_digits=4)),
                ('den', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
    ]
