# Generated by Django 2.2.19 on 2021-03-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_checkup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='use',
            field=models.CharField(default='user', max_length=20),
            preserve_default=False,
        ),
    ]
