# Generated by Django 2.2.19 on 2021-03-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_checkup', '0002_auto_20210328_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='sex',
            new_name='gen',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='use',
            new_name='user',
        ),
    ]
